version: '3.4'

services:
  db:
    image: postgres:16.3
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trailblazer
    ports:
      - '5532:5432'
    volumes:
      - ./db_dumps:/db_dumps
volumes:
  redis_data:
    driver: local
